config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user    #article can only be made by one user
    has_many :article_categories
    has_many :categories, through: :article_categories  # many-many implementation
    validates :title, presence: true, length: {minimum: 6, maximum: 100}    #title is needed to be present in every article + minimum and maximum length of them
    validates :description, presence: true, length: {minimum: 10, maximum: 300}  #same but with description
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord

    validates :name, presence: true, uniqueness: true, length: {minimum: 2, maximum: 20}
    has_many :article_categories
    has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email = email.downcase}   #I need to change to lowercase before saving an email into the databse, thats why i use before_save method
    has_many :articles  #One user can write and post many articles, defining a relation
    #constans are declared by names made out of caps letters only
    REGEX_FORM = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
    validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 5, maximum: 20}
    validates :email, presence: true, uniqueness: {case_sensitive: false}, length: {maximum: 50}, format: {with: REGEX_FORM}
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user #current_user is now available also to for example views, not only controllers
    def current_user    #returns detials of the currently logged user   || its a helper method
        if session[:user_id]
            @current_user ||=User.find(session[:user_id])   #that @current_user ||= lets memorize current user if they are actually logged in. that way we dont block db 
    
        end
    end

    helper_method :logged_in?
    def logged_in?
        !!current_user      #!! turns something into bool
    end

    helper_method :require_user
    def require_user #method used to restrict actions at the controller level (so they arent accesible just by changing the URL)
        if !logged_in?
            flash[:alert] = "You must be logged in first"
            redirect_to login_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    # before_action automatically performs chosen method before specified methods
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_correct_user, only: [:edit, :update, :destroy]
    def show
        
    end

    def index
        @articles = Article.paginate(page: params[:page], per_page: 5) #in place of "Article.all" to use pagination feature added with pagination gemfile
    end

    def new
        if !@article.presence   #my own version to be sure that @article isnt getting overwritten
        @article = Article.new
        end
    end

    def create
        @article = Article.new(article_params)
        @article.user=current_user
        if @article.save
            flash[:notice] = "article was created succesfully"
            redirect_to article_path(@article)
        else
            render 'new'
        end
        #render plain: @article.inspect
    end
    
    def edit
        
    end

    def update
        
        if @article.update(article_params)
            flash[:notice] = "Article was edited succesfully"
            redirect_to @article
        else
            render 'edit'
        end
    end

    def destroy
        
        @article.destroy
        redirect_to articles_path
    end
    
    private

    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description, category_ids: []) #whitelist an array of categories that are associated with specific article
    end

    def require_correct_user
        if current_user != @article.user && !current_user.admin?
            flash[:alert] = "You can't do that"
            redirect_to @article
        end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    before_action :require_admin, except: [:index, :show]

    def new
        @category = Category.new
    end

    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end

    def show
        @category = Category.find(params[:id])
        @articles=@category.articles.paginate(page: params[:page], per_page: 5)
    end

    def edit
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:notice] = "Category name changed"
            redirect_to @category
        else
            render 'edit'
        end
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category was created"
            redirect_to @category
        else
            render 'new'
        end
    end

    private

    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !(logged_in? && current_user.admin?)
            flash[:alert] = "You are not an admin"
            redirect_to categories_path
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        if logged_in?
        redirect_to articles_path
        end
    end
    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user=User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id # allows logged in users to stay signed in | Also user data is stored on the client side and encrypted
            flash[:notice] = "You are now logged in"
            redirect_to user
        else
            flash.now[:alert] = "Wrong login details"   #flash.now doesnt last for a whole http request so it will dissapear after changing path
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "You are now logged out"
        redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :set_user, only: [:show, :edit, :update]
    before_action :require_user, only: [:sedit, :action]
    before_action :require_correct_user, only: [:edit, :update]
    def new
        @user=User.new
    end

    def create
        @user=User.new(user_params)
        if @user.save
            session[:user_id] = @user.id    #user is automatically logged in after signing up
            flash[:notice] = "Welcome #{@user.username}"
            redirect_to @user
        else
            render 'new'
        end
    end

    def edit
        
    end

    def update
        
        if @user.update(user_params)
            flash[:notice] = "Account updated"
            redirect_to @user
        else
            render 'edit'
        end
    end

    def show
        
        @articles=@user.articles.paginate(page: params[:page], per_page: 5)
    end

    def index
        @users=User.paginate(page: params[:page], per_page: 5)
    end
    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def set_user
        @user=User.find(params[:id])
    end

    def require_correct_user
        if current_user != @user
            flash[:alert] = "You can't do that"
            redirect_to @user
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    

    

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class= "container">
<% @articles.each do |article| %>
    <div class="row justify-content-md-center">
    <div class="col-9 mt-2">
    <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
            <% if article.user %>
            by <%=link_to article.user.username, user_path(article.user) %>
            <% if article.categories.any? %>
                <br/>
                <div class ="mt-2"><%= render article.categories %></div>  <!-- _category partial in categories folder is ndeeded -->
            <% end %>
            <% end %>
        </div>
        <div class="card-body">
            <h5 class="card-title"><strong><%= link_to article.title, article_path(article.id), class: "articles-colors" %></strong></h5>
            <p class="card-text"><%= truncate(article.description, length: 50) %></p>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
                <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
            </div>
        <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago,
            edited <%= time_ago_in_words(article.updated_at) %> ago</small>
        </div>
    </div>
    </div>
    </div>
<% end %>
</div>
</div>

app/views/articles/_form.html.erb
<div class="container" id="edittt">

<%= render 'shared/errors', object: @article %>


<%= form_with(model: @article, class: "shadow-lg p-4 mb-3 bg-#6200b3 rounded", local: true) do |f| %>

    <div class="form-group row">
        <%= f.label :title, class: "col-2 col-form-label font-weight-bold" %>
        <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
        </div>
    </div>

    <div class="form-group row">
        <%= f.label :description, class: "col-2 col-form-label font-weight-bold" %>
        <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Descripton of article" %>
        </div>
    </div>

    <div class="form-group row">
        <%= f.label :category, class: "col-2 col-form-label font-weight-bold" %>
        <div class="col-10">
            <%= f.collection_select(:category_ids, Category.all, :id, :name, {prompt: "Choose categories from the list (or not)"}, {multiple: true, class: "custom-select shadow rounded"})%>
        </div>
    </div>

    <div class="form-group row justify-content-center">
        <%= f.submit class: "btn btn-outline-dark btn-lg"%>
    </div>
<% end %>
<p class="row justify-content-center mb-3">
<%= link_to '[ Cancel and return to articles listings ]', articles_path(), class: "text-dark" %>
</p>

</div>

app/views/articles/edit.html.erb
<div id="page-content">
<h1 class="text-center mt-4">Edit article</h1>

<p>
<%= render 'form' %>
</p>

</div>

app/views/articles/index.html.erb
<div id="page-content">
<h1 class="text-center mt-4">Articles listing page</h1>

<!-- allows pagination -->
<div class="apple_pagination">
     <%= will_paginate @articles, :container => false %>
</div>
<%= render 'article' %>
<div class="apple_pagination mb-4">
     <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<div id="page-content">
<h1 class="text-center mt-4">Create a new article</h1>

<p>
<%= render 'form' %>
</p>


</div>

app/views/articles/show.html.erb
<div class="w-auto", id="page-content">
<h1 class="text-center mt-3"><%= @article.title %></h1>



<div class="container">
<div class="row justify-content-md-center">
    <div class="col-9 mt-2">
    <div class="card text-center shadow mb-3 bg-white rounded">
        <div class="card-header font-italic">
            by <%=@article.user.username %>
            <% if @article.categories.any? %>
                <br/>
                <div class ="mt-2"><%= render @article.categories %></div>  <!-- _category partial in categories folder is ndeeded -->
            <% end %>
        </div>
        <div class="description-show text-left mx-4">
            <%= @article.description%>
        </div>
        <div class="card-body">
            
            <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
                <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
                <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
            </div>
        <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(@article.created_at) %> ago,
            edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
        </div>
    </div>
    <div class="row justify-content-center">
        <%= link_to '[ Return to articles listings ]', articles_path(), class: "text-dark mt-0" %>
    </div>
    </div>
</div>
</div>
</div>

app/views/categories/_category.html.erb
<span class="badge rounded-pill bg-dark text-light mr-1 ml-1"><%= link_to category.name, category_path(category), class: "text-light" %></span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', object: @category %>


<%= form_with(model: @category, class: "shadow-lg p-4 mb-3 bg-#6200b3 rounded", local: true) do |f| %>

    <div class="form-group row">
        <%= f.label :name, "Name", class: "col-2 col-form-label font-weight-bold" %>
        <div class="col-10">
        <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "category name" %>
        </div>
    </div>

    <div class="form-group row justify-content-center">
        <%= f.submit class: "btn btn-outline-dark btn-lg"%>
    </div>
<% end %>

app/views/categories/edit.html.erb
<div id="page-content">
<h1 class="text-center mt-4">Create a new category</h1>

<div class="container" id="edittt">
    <%= render 'form' %>
    
    <p class="row justify-content-center mb-3">
        <%= link_to '[ Cancel and return to categories listings ]', categories_path(), class: "text-dark" %>
    </p>

</div>


</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories listing</h1>

<!-- allows pagination -->
<div class="apple_pagination">
     <%= will_paginate @categories, :container => false %>
</div>



<div class= "container">
<% @categories.each do |category| %>
    <div class="row justify-content-md-center">
    <div class="col-4 mt-2">
    <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-body">
            <h5 class="card-title"><strong><%= link_to category.name, category_path(category), class: "articles-colors" %></strong></h5>
            <%= pluralize(category.articles.count, "article") %>
        </div>
        <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(category.created_at) %> ago,
            edited <%= time_ago_in_words(category.updated_at) %> ago</small>
        </div>
    </div>
    </div>
    </div>
<% end %>
</div>
</div>

<div class="apple_pagination mb-4">
     <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<div id="page-content">
<h1 class="text-center mt-4">Create a new category</h1>

<div class="container" id="edittt">

<%= render 'shared/errors', object: @category %>


<%= form_with(model: @category, class: "shadow-lg p-4 mb-3 bg-#6200b3 rounded", local: true) do |f| %>

    <div class="form-group row">
        <%= f.label :name, "Name", class: "col-2 col-form-label font-weight-bold" %>
        <div class="col-10">
        <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "category name" %>
        </div>
    </div>

    <div class="form-group row justify-content-center">
        <%= f.submit class: "btn btn-outline-dark btn-lg"%>
    </div>
<% end %>
<p class="row justify-content-center mb-3">
<%= link_to '[ Cancel and return to articles listings ]', articles_path(), class: "text-dark" %>
</p>

</div>


</div>

app/views/categories/show.html.erb
<div id="page-content">
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
     <div class="text-center mt-4"><%= link_to "Edit category", edit_category_path(@category), class: "btn btn-outline-info" %></div>
<% end %>

<div class="apple_pagination mb-2">
     <%= will_paginate @articles, :container => false %>
</div>
<h2 class="text-center mt-4">Articles</h2>
<%= render 'articles/article' %>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-3 bg-dark text-white-50">
    <div class="container text-center text-white">
        <small>Copyright &copy; <%= link_to "Jan Walczak", root_path, class: "text-white" %></small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    
    <div class="alert alert-<%= name == "notice" ? "succes" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      </button>
      </div>
    <% end %>
   
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
        
        <%= link_to "JW BLOG", root_path, class: "navbar-brand", id: "logo" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            
            <li class="nav-item">
              <%= link_to "Users", users_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Articles
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "View articles", articles_path, class: "dropdown-item" %>
                <% if logged_in? %>
                  <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
                <% end %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Categories
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "View categories", categories_path, class: "dropdown-item" %>
                <% if logged_in? && current_user.admin? %>
                  <%= link_to "Create new category", new_category_path, class: "dropdown-item" %>
                <% end %>
            </li>
            
            <% if logged_in? %>
              <li class="nav-item">
                <%= link_to current_user.username, user_path(current_user), class: "nav-link"%>
              </li>
              <li class="nav-item">
                <%= link_to "Log out", logout_path, class: "nav-link", method: :delete %>
              </li>
            <% else%>
              <li class="nav-item">
                <%= link_to "Log in", login_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Sign up", signup_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
          
        </div>
      </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="row justify-content-md-center">
    <div class="col-9 mt-2">
    <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
            
            by Jan Walczak
            
        </div>
        <div class="card-body">
            <h5 class="card-title"><strong>Jan Walczak</strong></h5>
            <p class="card-text">Dzień dobry. Strona ta powstała podczas mojej na razie krótkiej przygody z językiem Ruby na frameworku Rails. Głównymi źródłami, z których do tej pory korzystałem były:</p>
            <ul>
                <li><a href="https://www.udemy.com/course/the-complete-ruby-on-rails-developer-course/">Kurs Mashrura Hossaina na platformie udemy.com</a></li>
                <li>Repozytoria na platformie GitHub</li>
                <li>Specyfikacja Ruby on Rails</li>
            </ul>
        </div>
        
    </div>
    </div>
    </div>

app/views/pages/home.html.erb
<div id="page-content">
<div class="container" id="home-container">
        <div class="jumbotron text-center text-white">
            <h1 class="display-4">JW BLOG</h1>
            <p class="lead">This is a simple blog-like app project. Feel free to check it out</p>
            <hr class="my-4">
            
            <%= link_to "Sign up!", signup_path, class: "btn btn-primary btn-lg"%>
        </div>
</div>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <h4 class="alert-heading">The following errors prevented <%= object.class.name.downcase %> from being saved</h4><!--its necessary to use.name there because .dwoncase needs it to wrok-->
  <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end%>

app/views/users/_form.html.erb
<div class="container" id="edittt">

<%= render 'shared/errors', object: @user %>


<%= form_with(model: @user, class: "shadow-lg p-4 mb-3 bg-#6200b3 rounded", local: true) do |f| %>

    <div class="form-group row">
        <%= f.label :username, class: "col-2 col-form-label font-weight-bold" %>
        <div class="col-10">
        <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "xyz" %>
        </div>
    </div>

    <div class="form-group row">
        <%= f.label :email, class: "col-2 col-form-label font-weight-bold" %>
        <div class="col-10">
        <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "123@xyz.com" %>
        </div>
    </div>

    <div class="form-group row">
        <%= f.label :password, class: "col-2 col-form-label font-weight-bold" %>
        <div class="col-10">
        <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "***" %>
        </div>
    </div>

    <div class="form-group row justify-content-center">
        <%= f.submit(@user.new_record? ? "Sing up" : "Update account", class: "btn btn-outline-dark btn-lg")%>
    </div>
<% end %>
<p class="row justify-content-center mb-3">
<%= link_to '[ Cancel and return to articles listings ]', articles_path(), class: "text-dark" %>
</p>

</div>

app/views/users/edit.html.erb
<div id="page-content">
<h1 class="text-center mt-4">Edit profile</h1>

<p>
<%= render 'form' %>
</p>


</div>

app/views/users/index.html.erb
<div id="page-content">
<h1 class="text-center mt-4">Users</h1>

<div class="apple_pagination mb-4">
     <%= will_paginate @users, :container => false %>
</div>

<div class= "container">
<% @users.each do |user| %>
    <div class="row justify-content-md-center">
    <div class="col-9 mt-2">
    <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
            <%= pluralize(user.articles.count, "article") %> <!-- pluralize helps in writing the correct form of the noun "article", depending on the number of the articles-->
        </div>
        <div class="card-body">
            <h5 class="card-title"><strong><%= user.username%></strong></h5>
            <%= link_to "View", user_path(user), class: "btn btn-outline-success" %>
            <% if logged_in? && user == current_user %>
                <%= link_to "Edit", edit_user_path(user), class: "btn btn-outline-info" %>
            <% end %>
            </div>
        <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(user.created_at) %> ago,
            edited <%= time_ago_in_words(user.updated_at) %> ago</small>
        </div>
    </div>
    </div>
    </div>
<% end %>
</div>
</div>

app/views/users/new.html.erb
<div id="page-content">
<h1 class="text-center mt-4">Sign up</h1>

<p>
<%= render 'form' %>
</p>


</div>

app/views/users/show.html.erb
<div id="page-content">
<h1 class="text-center mt-4"><%= @user.username %></h1>

<% if logged_in? && @user == current_user %>
     <div class="text-center mt-4"><%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %></div>
<% end %>

<div class="apple_pagination mb-2">
     <%= will_paginate @articles, :container => false %>
</div>
<h2 class="text-center mt-4">Articles</h2>
<%= render 'articles/article' %>